global:
  scrape_interval: 1s
  external_labels:
    monitor: 'ice-hockey-manager'

scrape_configs:
  - job_name: 'core'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['core:8080']
  - job_name: 'game-scheduler'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'game-scheduler:8082' ]
  - job_name: 'league-table'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'league-table:8083' ]
