spring:
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/ice-hockey-manager
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
